### ISSUE TITLE
Error: Unable to write to User Settings because terminal.integrated.rendererType 

### ISSUE THREAD

**Issue by 666XD** [EYHN/vscode-vibrancy#101]
Try to install the extension on Vscode(1.56.0) and MacOs 11.3.1 but failed 

The error message like below:
`Something went wrong: Error: Unable to write to User Settings because terminal.integrated.rendererType is not a registered configuration.`

And when I try to force reload vibrancy get this message
`Command 'Reload Vibrancy' resulted in an error (Running the contributed command: 'extension.updateVibrancy' failed.)`

I didn't find `terminal.integrated.rendererType` anywhere in Vscode. How to fix this?

**Comment by BIKA-C** [comment]
see this #100 issue.

The original setting `"terminal.integrated.rendererType": "dom"` is deprecated.
Use this instead: `"terminal.integrated.gpuAcceleration": "off"`

You might want to:
1.  install the extension in the 1.55 version vscode
2. Then upgrade the vscode to 1.56.
3. Add `"terminal.integrated.gpuAcceleration": "off"` to your settings.json

Still waiting for someone to officially fix this issue

**Comment by sortedcord** [comment]
I think this has got to do something with the permissions as well. I tried the steps mentioned by @BIKA-C and they worked but when I tried to change the extension settings, I was getting the same error. When I opened my `settings.json` file, the file was omitted but wasn't saved. So I saved it & restarted code, and It worked.....

**Comment by 666XD** [comment]
Things turn out that the `Reload Vibrancy` still doesn't work and it still announce the error after install, but the theme change after I restart the Vscode manually without any modifications. 
Thanks for answering!

**Comment by EYHN** [comment]
Thanks for the heads up guys, I've fixed this in 1.0.15. Please make sure you have upgraded to the latest version.
