### ISSUE TITLE
Vibrancy Not working for integrated terminal

### ISSUE THREAD

**Issue by lkm14001** [EYHN/vscode-vibrancy#103]
Even if I type  "teminal.integrated.rendererType" : "dom"  in settings.json file

It is not working even after that.

please give a solution

**Comment by Vbner** [comment]
I'm new in this github thing but i found the same problem as you and some guys told me that the oldest method doesn't work but if you write  "terminal.integrated.gpuAcceleration": "off"  in settings.json file it should work, because for me it did work. Take care !!

**Comment by Vbner** [comment]
They told me that "terminal.integrated.gpuAcceleration": "off" is the same as if you write "teminal.integrated.rendererType" : "dom" so it would be fine.

**Comment by EYHN** [comment]
Make sure you have upgraded your vscode version to 1.56.2

**Comment by EYHN** [comment]
If the problem is not resolved, please update this issue.
