### ISSUE TITLE
Acrylic not functioning as expected, appears for second then disappears 1.0.15

### ISSUE THREAD

**Issue by dudeisbrendan03** [EYHN/vscode-vibrancy#106]
Appears to function for a second, then proceeds to go back to normal.
There's some theming, but acrylic isn't working at all.
![image](https://user-images.githubusercontent.com/6009600/120388330-e3051e80-c322-11eb-808f-56a3cfd4c6d5.png)

Nothing super useful in dev tools, fresh install of 1.57.0-insider.

An example of the installation process I go through and what's happening is attached

![Video containing an example of the installation process of Vibrancy and VSCode insiders](https://cdn.thatspretty.cool/box/brendantdj/recordedVideo.mp4)
(If GitHub gets upset about the filesize of the video you can view it [here](https://cdn.thatspretty.cool/box/brendantdj/recordedVideo.mp4) instead)

Edit: GitHub did get angry about it, you can still view it here [https://cdn.thatspretty.cool/box/brendantdj/recordedVideo.mp4](https://cdn.thatspretty.cool/box/brendantdj/recordedVideo.mp4)

**Comment by EYHN** [comment]
Thank you for reporting the problem, I will look into it as soon as possible, until then please use vscode 1.56.2.

**Comment by avanishsubbiah** [comment]
Yeah, I'm having this same issue in 1.57.0 insider

**Comment by BIKA-C** [comment]
same here, 1.57.0

**Comment by mkanet** [comment]
It looks like this issue has also reached the regular non-insider build too. v1.57.0

**Comment by EYHN** [comment]
I'm still researching the cause of this issue.

**Comment by denewito** [comment]
Same issue here, please help.
Fresh installation, fresh windows 10 on new PC

**Comment by JorDindi** [comment]
For everyone who having problem with version 1.57.0,

Please stop complaining its not working and let the man work out on it.
He literally commented use version 1.56.2 until he updates the extension.

Jesus..

**Comment by EYHN** [comment]
Hi, I have fixed this problem in vscode-vibrancy 1.0.16-rc1.
I have not released it in the vscode extension marketplace. You can download the .vsix from here and install it manually.
https://github.com/EYHN/vscode-vibrancy/releases/tag/1.0.16-rc1

I will publish the version in the vscode extension marketplace when the test is complete.

**Comment by EYHN** [comment]
Hi, I have fixed this problem and make sure you have upgraded this extension to v1.0.16.

If the problem is not resolved, please update this issue.

**Comment by mkanet** [comment]
@EYHN I can confirm the fix works correctly for me.  I'm glad the fix was relatively minor.

**Comment by mkanet** [comment]
@EYHN Actually, there seems to be an odd issue with it.  When I maximize VSCode or restore it back to a window, it briefly switches the transparent background to a weird transparent light color.  The same way it does when first starting VSCode.  It didn't use to do this before.

**Comment by shoucandanghehe** [comment]
@mkanet 
I think there is indeed this problem
I also found that he would appear temporarily opaque

**Comment by EYHN** [comment]
@mkanet @shoucandanghehe  The current solution does have flickering problems and I am looking for a better solution.

**Comment by mkanet** [comment]
I'm curious, is there a reason why this issue is closed?

**Comment by IgnusG** [comment]
> I'm curious, is there a reason why this issue is closed?

The original issue is fixed I assume. The new issue with the solution is that it sometimes flickers in and out so maybe a new issue thread would be good @EYHN?
