### ISSUE TITLE
Editor keeps being solid color.

### ISSUE THREAD

**Issue by JorDindi** [EYHN/vscode-vibrancy#107]
<h1 align="center">Hi 👋</h1>
<h3 align="center">Everything working fine, just the editor keeps on being solid color, cannot fix it, please help.</h3>

Using version 1.56.2
![image](https://i2.paste.pics/ef9ac47a74e0569794e3f5576be0e58b.png)

**Comment by EYHN** [comment]
Hi, I have fixed this problem in vscode-vibrancy 1.0.16-rc1.
I have not released it in the vscode extension marketplace. You can download the .vsix from here and install it manually.
https://github.com/EYHN/vscode-vibrancy/releases/tag/1.0.16-rc1

I will publish the version in the vscode extension marketplace when the test is complete.

**Comment by EYHN** [comment]
Hi, I have fixed this problem and make sure you have upgraded this extension to v1.0.16.

If the problem is not resolved, please update this issue.
