### ISSUE TITLE
VS Code 1.57 breaks Vibrancy (Do not update to 1.57)

### ISSUE THREAD

**Issue by lor1x** [EYHN/vscode-vibrancy#108]
Hi,

After updating to 1.57 yesterday Vibrancy stopped working, not entirely. When VS Code is starting up I can see it being rendered then overwritten once everything loads. The acrylic effect lasts only for the load time then it is solid color of the theme I’m using. 

I tried this on macOS Big Sur 11.4 and Windows 10 21H1, even on clean installs of VS Code (with just Vibrancy on it), same thing. I have downgraded to 1.56.2 for now and blocked updates.

Anyone else having this issue as well?

**Comment by denewito** [comment]
is Vibrancy working for 1.56.2 ?

**Comment by lor1x** [comment]
Yes it works just fine, I downgraded to 1.56.2 and blocked updates for now @denewito

**Comment by theXiaoWang** [comment]
I exactly encountered this as well it took me quite a while to find whether someone has the same problem. This is so dumb, I'm switching to jetbrain ide now, it has a similar plugin called GlassCode. Works perfectly.
![Untitled](https://user-images.githubusercontent.com/84678151/121751318-caa4b900-cb05-11eb-83dc-f298e6206bb1.png)

**Comment by Rasmagoric** [comment]
Yeah can confirm, it broke for me too in VS Code 1.57

**Comment by denewito** [comment]
Doesn't work in 1.56.2  for me. :(

**Comment by sohancms** [comment]
After getting the update vs code vibrancy gonna stop. My heart is break for that case .What can I do for this case

**Comment by lor1x** [comment]
@denewito Try to reinstall Vibrancy, are you using something like Customize UI too?

@sohancms Well you can downgrade, download 1.56.2 from [here](https://code.visualstudio.com/updates/v1_56) and before starting the installer save this to your preferences json file:
`"update.mode": "none"`

**Comment by Dgdaniel** [comment]
> is Vibrancy working for 1.56.2 ?

yes, I have installed it, and it was working before I make the upgrade of vs code to the 1.57

**Comment by sohancms** [comment]
after getting the upgrade it's not working..

**Comment by Talk2dilshad** [comment]
fix it please fast
@Rasmagoric

**Comment by JotaRata** [comment]
Color theme changes but no transparency is applied

**Comment by BranislavZivanovic** [comment]
> @denewito Try to reinstall Vibrancy, are you using something like Customize UI too?
> 
> @sohancms Well you can downgrade, download 1.56.2 from [here](https://code.visualstudio.com/updates/v1_56) and before starting the installer save this to your preferences json file:
> `"update.mode": "none"`

Can you please explain how can i prevent vscode from autoupdate? Where can i find the preferences json file?

**Comment by Talk2dilshad** [comment]
I made it already but this theme need to fix this bug it's important and
the terminal is not also getting transparent glass effect

**Comment by lor1x** [comment]
Open the Command Palette (check more [here](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)) then search settings json and it should show up. Open it, add that line inside the brackets then save it. After you have done that you can downgrade and it won’t auto update. @BranislavZivanovic

**Comment by rashil2000** [comment]
Facing the same issue (no transparency) with 1.57.

Apart from the new safety features, VSCode also made some UI changes, like https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors

**Comment by kaganergovan** [comment]
I got same problem. Just downgraded to this:

> > @denewito Try to reinstall Vibrancy, are you using something like Customize UI too?
> > @sohancms Well you can downgrade, download 1.56.2 from [here](https://code.visualstudio.com/updates/v1_56) and before starting the installer save this to your preferences json file:
> > `"update.mode": "none"`
> 
> Can you please explain how can i prevent vscode from autoupdate? Where can i find the preferences json file?

and works fine right now. Also I'm getting 

> Your Code installation appears to be corrupt. Please reinstall.

for while. Any updates?

**Comment by lor1x** [comment]
@kaganergovan 
https://github.com/EYHN/vscode-vibrancy/issues/95

**Comment by EYHN** [comment]
Hi, I have fixed this problem in vscode-vibrancy 1.0.16-rc1.
I have not released it in the vscode extension marketplace. You can download the .vsix from here and install it manually.
https://github.com/EYHN/vscode-vibrancy/releases/tag/1.0.16-rc1

I will publish the version in the vscode extension marketplace when the test is complete.

**Comment by lor1x** [comment]
Perfect! Thank you!

**Comment by EYHN** [comment]
Hi, I have fixed this problem and make sure you have upgraded this extension to v1.0.16.

If the problem is not resolved, please update this issue.

**Comment by sohancms** [comment]
Thank you dear

**Comment by sohancms** [comment]
lor1x v1.0.16 extension is working. But it’s flickering very few time. However thanks a lot dear EYHAN and lor1x

**Comment by EYHN** [comment]
@sohancms The current solution does have flickering problems and I am looking for a better solution.

**Comment by Talk2dilshad** [comment]
when I do full-screen mode (F11) vibrancy won't work there too. and flickering lot
