### ISSUE TITLE
The transparency decreases very quickly to 0 when VSCode is restarted

### ISSUE THREAD

**Issue by Impre-visible** [EYHN/vscode-vibrancy#110]
Like said in the title, when i start VSCode, the transparency is at 0.7, and after 2sec, the transparency is at 0.

My JSON Settings :

{
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },
    "[css]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.formatOnSave": true
    },
    "discord.detailsDebugging": "Débug {filename}",
    "discord.detailsEditing": "Modifie {filename}",
    "discord.largeImage": "Edit un fichier en {LANG}",
    "discord.lowerDetailsNotFound": "dsc.bio/imprevisible",
    "workbench.iconTheme": "helium-icon-theme",
    "explorer.confirmDelete": false,
    "helium-icon-theme.folders.color": "#ff7043",
    "helium-icon-theme.folders.theme": "specific",
    "helium-icon-theme.activeIconPack": "angular_ngrx",
    "helium-icon-theme.hidesExplorerArrows": false,
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": -1,
    "terminal.integrated.gpuAcceleration": "yes",
    "vscode_vibrancy.opacity": 0.7
}

**Comment by EYHN** [comment]
Hi, I have fixed this problem and make sure you have upgraded this extension to v1.0.16.

If the problem is not resolved, please update this issue.
