### ISSUE TITLE
安装插件后拖动vscode有延迟

### ISSUE THREAD

**Issue by WangTingZheng** [EYHN/vscode-vibrancy#16]
系统：windows 10；
安装插件后毛玻璃效果正常，拖动的时候会出现两个鼠标，拖动的时候会有比较严重的延迟

**Comment by YoungSx** [comment]
我这里也是，拖动窗口严重延迟

**Comment by lizhihao6** [comment]
+1

**Comment by WangTingZheng** [comment]
@EYHN 看来这个问题挺普遍的，毛玻璃效果很好看，只是这个延迟真的很难受，要是能修复就完美了！

**Comment by EYHN** [comment]
Please move to #5
