### ISSUE TITLE
开启后无法禁用

### ISSUE THREAD

**Issue by YoungSx** [EYHN/vscode-vibrancy#17]
VSCode: 1.37.1
Vibrancy: 1.0.6
不论是 disable 还是 uninstall 都无法禁用，重启 VSCode 也没效果。

**Comment by dioxygen** [comment]
我更新vscode之后好了。。。

**Comment by EYHN** [comment]
https://github.com/EYHN/vscode-vibrancy#how-to-uninstall

Press F1 and Activate command "Disable Vibrancy", and Restart Visual Studio Code.
