### ISSUE TITLE
开启后在桌面是没有毛玻璃效果，覆盖在其他窗口上是有的

### ISSUE THREAD

**Issue by NaokiLH** [EYHN/vscode-vibrancy#18]

**Comment by EYHN** [comment]
请提供更多信息，图片或者视频.

Please more information

**Comment by NaokiLH** [comment]
![Z3Q}I}I1P ~OZ2ZGEKJ46ZW](https://user-images.githubusercontent.com/43508737/64878152-7432ee00-d685-11e9-8529-83e03a1f3c4f.png)
![U$8 ~{LU6(C5FQT$KG @4JV](https://user-images.githubusercontent.com/43508737/64878155-75fcb180-d685-11e9-9417-a89bbc9093f7.png)
