### ISSUE TITLE
Set Only Sidebar / Activity bar to transparent

### ISSUE THREAD

**Issue by a5l3** [EYHN/vscode-vibrancy#19]
Hi 💯 
Great extension.
Currently there is no option to choose which part of Vscode can be set with a specific vibrancy.
How could I set only the vibrancy for sidebar and/or the activity bar?

**Comment by EYHN** [comment]
I created a new theme called "Dark (Only Subbar)", you can switch to the theme as shown below.

![image](https://user-images.githubusercontent.com/13579374/64470048-2131d600-d16f-11e9-9d57-39a5dedffefa.png)
