### ISSUE TITLE
Unable to remove

### ISSUE THREAD

**Issue by smith** [EYHN/vscode-vibrancy#21]
After uninstalling the extension it still seems to be in effect. How do I remove the customizations and reset back to the VSCode defaults?

**Comment by smith** [comment]
It did eventually go away, but I had to quit and restart vscode about 3 times.

**Comment by stefnotch** [comment]
The FAQs (now) contain a bit of info about this.

https://github.com/EYHN/vscode-vibrancy/blob/master/README.md#how-to-uninstall
