### ISSUE TITLE
Does not work with Peacock extension

### ISSUE THREAD

**Issue by smith** [EYHN/vscode-vibrancy#22]
When using the [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension, after install vibrancy the sidebar is dark and you can't see the icons, and the peacock color is not shown (supposed to be cyan in this screenshot) 
![image](https://user-images.githubusercontent.com/9912/64638480-7833e700-d3cb-11e9-9afb-9c8da36f030b.png)

**Comment by EYHN** [comment]
Peacock and vscode-vibrancy changed styles at the same time.
It is difficult to be compatible.

**Comment by TiagoDanin** [comment]
Same problem. 
@smith solution and change color to Peacock.
![image](https://user-images.githubusercontent.com/5731176/165087618-a1027cfd-0200-482c-ba9d-9e134bfdb6ba.png)
![image](https://user-images.githubusercontent.com/5731176/165087649-90550318-e138-4ac2-8c25-db8489063595.png)
