### ISSUE TITLE
White Line at the top of the window on Current Insider(1.39) when maximized

### ISSUE THREAD

**Issue by ShubhamBelwal** [EYHN/vscode-vibrancy#23]
I'm using the extension in the current insider. VSCode Details:
![image](https://user-images.githubusercontent.com/36201797/65268557-08dd9600-db35-11e9-8f30-67d71aee78ae.png).

When maximizing the VSCode Windows, a white line appears at the top.
![VSCode](https://user-images.githubusercontent.com/36201797/65268608-24e13780-db35-11e9-9794-62a9495b19a2.png)

**Comment by qxdn** [comment]
+1

**Comment by ShubhamBelwal** [comment]
Looks like this is related to [Themable Window Border](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_40.md#themable-window-border) introduced in VSCode 1.40. 

Can we get an update on this?

**Comment by qxdn** [comment]
![image](https://user-images.githubusercontent.com/42409827/68586873-9fd52780-04c0-11ea-9adf-43c79aa3e3d4.png)
1.40 still has this problem.
I try to change "window.activeBorder",but still has the line.

**Comment by EYHN** [comment]
I can't reproduce this problem, please try to reinstall this extension and vscode.
