### ISSUE TITLE
安装毛玻璃效果后，整个 vs code 变白

### ISSUE THREAD

**Issue by RekiDunois** [EYHN/vscode-vibrancy#24]
![image](https://user-images.githubusercontent.com/23435534/65406958-9a8a2380-de13-11e9-8556-ca29078228dd.png)

标题描述的可能不是很好，具体效果如上图，运行 Reload Vibrancy 之后就变成这样了。

以下我使用的 vs code 以及系统版本

![image](https://user-images.githubusercontent.com/23435534/65407104-08364f80-de14-11e9-9772-ffb2a5d0f23d.png)

这应该会是系统的问题还是什么问题呢？

**Comment by EYHN** [comment]
试试新版本呢？issues太久了
