### ISSUE TITLE
Allow other themes?

### ISSUE THREAD

**Issue by alexa-griffin** [EYHN/vscode-vibrancy#26]
Love the extension and the effect it gives however is there a way to either auto detect the theme background or allow the user to set it?

**Comment by alexa-griffin** [comment]
So after quite a bit of hacking i have come up with this super jerryrigged solution:
- install vibrancy normally
- open the extension code where ever that is for me it was `%USER%/extensionss/eyhn.vscode-vibrancy-1.0.7`
- in `themes` duplicate the theme you want to start from (in my case Dark (Only Subbar)) and change names as needed
- in the background field in the json file you created place the background color you want *in bgr format*, meaning `#ff0000` is perfect blue, `#0000ff` is perfect red, etc.
- in `src/extension.js` modify `themeStylePaths` and `themeConfigPaths` to include your new files
- in `package.json` change `contributes/configuration/properties/vscode_vibrancy.theme/enum` to include the name of your theme
- restart and apply as needed

hope this helps someone else who is hopelessly addicted to their theme and currently procrastinating by attempting to configure their ide in a meaningless but aesthetically pleasing way :)

**Comment by EYHN** [comment]
You can use https://github.com/be5invis/vscode-custom-css to patching your custom css.
