### ISSUE TITLE
No blur effect on just 1 PC

### ISSUE THREAD

**Issue by mkanet** [EYHN/vscode-vibrancy#27]
I am curious, do you know what could prevent **blur-cli.exe** to apply blur effect to VSCode on my Win10 work laptop?  I don't have any issues with Vibrancy on any of my PCs; except for my work laptop.  Below, is what it looks like.  Maybe, this is caused by my work laptop's antivirus blocking blur-cli.exe or having too many restrictions on the OS?  My work laptop's Start Menu definitely has blur effect as well as other windows components.

![No-Blur-blur-cli](https://user-images.githubusercontent.com/811008/66600183-d3d3ca80-eb59-11e9-8097-5ab73140bd94.png)

**Comment by EYHN** [comment]
If the problem persists, please reopen it.
