### ISSUE TITLE
macos 需要管理员权限运行vsocd 才能写入

### ISSUE THREAD

**Issue by Leeesin** [EYHN/vscode-vibrancy#28]
怎么管理员运行啊

**Comment by 121sss** [comment]
关闭VSCode app，在终端输入sudo "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"

**Comment by EYHN** [comment]
Which version of macos?

**Comment by zqcccc** [comment]
我也提示这个需要管理员权限，但是我已经是 root 权限启动了，还提示 cannot read property 'macos' of underfined
另外说一下，vscode 版本 1.40.0，系统是 catalina 10.15.1

**Comment by EYHN** [comment]
我刚刚升级到了 macos catalina 10.15.1 没有发现类似问题

**Comment by EYHN** [comment]
无法复现
