### ISSUE TITLE
请问macOS Catalina下是否可以在用此插件开启毛玻璃效果的同时，将主题设置为自己写好的.js和.css文件？

### ISSUE THREAD

**Issue by 121sss** [EYHN/vscode-vibrancy#30]
平台：macOS Catalina
VSCode版本：1.39.2

问题：在使用custom css and js loader插件更换主题后，使用vibrancy插件无法实现毛玻璃效果。已经在Vscode_vibrancy: Imports中导入了css文件和js文件的路径，仍提示“你当前颜色主题是‘synwave'84’，而你的毛玻璃主题是为‘default dark +’设计的”，我重启后无法开启毛玻璃效果

非常希望能够解决一下，不知道是不是macOS新系统的问题

截图：
<img width="701" alt="image" src="https://user-images.githubusercontent.com/50314455/67387839-38ffd500-f5ca-11e9-9681-f0b89e8a6286.png">

<img width="923" alt="image" src="https://user-images.githubusercontent.com/50314455/67387894-546ae000-f5ca-11e9-8f09-f22b86fcf03e.png">
<img width="924" alt="image" src="https://user-images.githubusercontent.com/50314455/67388077-98f67b80-f5ca-11e9-8c3b-305e86fdea6c.png">

**Comment by EYHN** [comment]
我的 macbook pro 还没升级到 macOS Catalina，晚点我升级看看

**Comment by 121sss** [comment]
> 我的 macbook pro 还没升级到 macOS Catalina，晚点我升级看看

好的，非常感谢！
另外，毛玻璃效果中的appearance-based是个非常有意思的特性，请问是否也可以允许用户导入主题呢，以实现根据macOS/Windows的深色/浅色模式的切换来切换用户导入主题的效果。

**Comment by Gyang18** [comment]
我也遇到了同样的问题

**Comment by Gyang18** [comment]
并且我的是在打开编辑器的时候能看到编辑器效果，可是当编辑器完全打开项目后，效果就消失了

**Comment by EYHN** [comment]
我升级到了 macOS Catalina 10.15.1 好像没什么问题。。。

**Comment by Gyang18** [comment]
![image](https://user-images.githubusercontent.com/24975063/68861439-859c8300-0726-11ea-94e7-9c33437b164d.png)
这是我的配置，我的是真的没有效果，vscode是最新版，或者能看下你的配置吗

**Comment by EYHN** [comment]
你默认设置有效果吗？

**Comment by EYHN** [comment]
会不会是你 custom css and js loader 注入的 css 文件中给 vscode 设置了背景颜色
导致模糊效果失效了
