### ISSUE TITLE
Dragging window around desktop is very slow and laggy

### ISSUE THREAD

**Issue by JamesLear92** [EYHN/vscode-vibrancy#34]
**ENVIRONMENT:** 

- Vibrancy 1.0.7
- VSCode  1.39.2
- Windows 1903 18362.1
- Resolution: 1440p

**ISSUE:**
When the window is not maximised, dragging the window to move it is very sluggish and "rubberbanding"
Performance inside window is fine, only moving the window.

**Comment by ymd45921** [comment]
I have same problem

**Comment by EYHN** [comment]
Same issues: https://github.com/EYHN/vscode-vibrancy/issues/5#issuecomment-546591977
