### ISSUE TITLE
An unexpected white ege when maxmize window

### ISSUE THREAD

**Issue by ymd45921** [EYHN/vscode-vibrancy#35]
Environment : 
Visual Studio Code 1.40.0

Issue : 
As the screenshot below.
![image](https://user-images.githubusercontent.com/44066908/68723011-4ec55080-05f2-11ea-8bce-8e7b10c3a087.png)
When maximize window, there is an unexpected white edge appear at top of the window.

**Comment by ymd45921** [comment]
Display Resolution : 1440p * 2
OS : Windows 10 1903 Educational Edition
Plugin Version : Vibrancy 1.0.7

**Comment by lieven121** [comment]
Can confirm 
also happens on 
1909 Pro
Vibrancy 1.0.7
1920p

**Comment by EYHN** [comment]
same: https://github.com/EYHN/vscode-vibrancy/issues/23
