### ISSUE TITLE
拖动窗口有延迟。

### ISSUE THREAD

**Issue by Diomchen** [EYHN/vscode-vibrancy#37]
效果出来了，但是拖动窗口延迟较高。

**Comment by Binning42** [comment]
我也是，延迟很高，只能全屏和分屏

**Comment by mashiro01** [comment]
感觉延迟有点高，不太舒服

**Comment by Rayree** [comment]
win10系统，同样是拖动窗口延迟很高，尝试卸载插件后延迟还是存在

**Comment by Lightcolour-666** [comment]
我也是

**Comment by EYHN** [comment]
see here: https://github.com/EYHN/vscode-vibrancy/issues/5#issuecomment-546591977

**Comment by huhuime** [comment]
如果安装了[Aero Glass](https://glass8.eu/guide) （传统程序标题栏加毛玻璃的玩意，该程序对DWM渲染引擎进行了扩展）可以考虑改代码强制走毛玻璃效果类型中的dwm，就没有拖动窗口延迟了
修改%UserProfile%\.vscode\extensions\eyhn.vscode-vibrancy-1.0.9\src\extension.js
注销掉第143行`opacity = 0;`及第197行`os === 'win10' ||`
再修改扩展配置中透明度和毛玻璃效果类型为dwm最后重载

**Comment by Blame4** [comment]
说来奇怪，我的主机没事，笔记本有延迟
