### ISSUE TITLE
Customization of what is vibrant.

### ISSUE THREAD

**Issue by drewswaycool** [EYHN/vscode-vibrancy#4]
It would be nice if you could specifiy what elements to be "vibrant".. i.e. only the side bar.. or only the active tab.

**Comment by AmrBinBashir** [comment]
for now you can fork this extension and make your modification to src/extension.js. The integrated chrome developer tools can help you know what element you want to change. It would be nice if the extension used a custom html page.

**Comment by EYHN** [comment]
Thanks for feedback. I will release this feature in the next version.

**Comment by AmrBinBashir** [comment]
> Thanks for feedback. I will release this feature in the next version.

Can you please make the blur effect more transparent or at least some options to choose from.

**Comment by EYHN** [comment]
@AmrBinBashir

https://github.com/EYHN/vscode-vibrancy/blob/master/README.md#vscode_vibrancyopacity-windows-only

An opacity option has been added to the new version.

**Comment by AmrBinBashir** [comment]
@EYHN 
thank you gonna try it now.

**Comment by EYHN** [comment]
Sorry to keep you waiting. @AmrBinBashir 
Theme system and custom CSS/JS have been released in v1.0.4. Please update your extension.
In addition, I also created a new theme called "Dark (Only Subbar)", you can switch to the theme as shown below.

![image](https://user-images.githubusercontent.com/13579374/61958410-d8292680-aff3-11e9-8be6-56e674f0d7a9.png)
