### ISSUE TITLE
mac mini not work please help~

### ISSUE THREAD

**Issue by HotWordland** [EYHN/vscode-vibrancy#41]
![01](https://user-images.githubusercontent.com/6984865/71650891-4c5eb780-2d54-11ea-9a46-b713710cf07d.gif)
I installed and enabled but not work... please help~ 
mac mini 10.14.4 (18E226)

**Comment by EYHN** [comment]
Does the other software in macos have blur effect ?

**Comment by EYHN** [comment]
Try the latest version. If the problem is not resolved, please update this issue.
