### ISSUE TITLE
Why not support Linux

### ISSUE THREAD

**Issue by Jontyshaw** [EYHN/vscode-vibrancy#42]
As a Linux lover, I like working in Linux

**Comment by JamesLear92** [comment]
There are vibrancy APIs available in both Windows and Mac, but I don't think there is one for Linux. I know you can blur, but it's not the same as acrylic/vibrancy

**Comment by EYHN** [comment]
same: https://github.com/EYHN/vscode-vibrancy/issues/20

**Comment by phoenix277yt** [comment]
so cant you just make a blur extension and then add noise? linux supports that, atleast arch.
