### ISSUE TITLE
The activity bar doesn't work well with the theme "default light" in version 1.41.1

### ISSUE THREAD

**Issue by DevilHandCC** [EYHN/vscode-vibrancy#43]
![image](https://user-images.githubusercontent.com/24727765/73708586-beeafa80-4739-11ea-81a9-3f58b6d3c505.png)

**Comment by DevilHandCC** [comment]
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by KhushrajRathod** [comment]
@EYHN Any updates on this?

**Comment by EYHN** [comment]
Try the latest version. If the problem is not resolved, please update this issue.
