### ISSUE TITLE
vscode update to 1.42.1 , vibrancy not work

### ISSUE THREAD

**Issue by lyfunny** [EYHN/vscode-vibrancy#44]
before updates it works well,  please Check compatibility

**Comment by github-account1111** [comment]
Did you make sure to `Reload Vibrancy`?

**Comment by lyfunny** [comment]
now works okay,i don't know what happened,but I'm sure i have reloaded
vibrancy many times after updated

github-account1111 <notifications@github.com> 于 2020年2月26日周三 11:28写道：

**Comment by github-account1111** [comment]
Then I'd suggest closing the issue.

**Comment by you-hengh** [comment]
版本: 1.43.0
提交: 78a4c91400152c0f27ba4d363eb56d2835f9903a
日期: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 16.7.0


Plug-in is invalid

Please adapt the latest version

**Comment by RungeCC** [comment]
版本: 1.46.0-insider (user setup)
提交: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
日期: 2020-05-13T18:20:10.752Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19613

Vibrancy does not work.

**Comment by you-hengh** [comment]
> 版本: 1.46.0-insider (user setup)
> 提交: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
> 日期: 2020-05-13T18:20:10.752Z
> Electron: 7.2.4
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.19613
> 
> Vibrancy does not work.
You can use F1 in vscode and select reload vibrancy to restart vscode for normal use

**Comment by RungeCC** [comment]
> > 版本: 1.46.0-insider (user setup)
> > 提交: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
> > 日期: 2020-05-13T18:20:10.752Z
> > Electron: 7.2.4
> > Chrome: 78.0.3904.130
> > Node.js: 12.8.1
> > V8: 7.8.279.23-electron.0
> > OS: Windows_NT x64 10.0.19613
> > Vibrancy does not work.
> > You can use F1 in vscode and select reload vibrancy to restart vscode for normal use

thanks. I solve it by re-install the ext.
