### ISSUE TITLE
1909在安装Aero Glass（glass8）调用dwm实现拖动窗口是无延迟，可否放开判定为win10后对选择dwm限制

### ISSUE THREAD

**Issue by huhuime** [EYHN/vscode-vibrancy#46]
1909在安装（[Aero Glass](https://glass8.eu/)）调用dwm效果
![GIF](https://user-images.githubusercontent.com/6631239/75537198-8cd76a80-5a51-11ea-81d3-6896e927d7c6.gif)
（图片大小5M！）可否考虑放开判定为win10后对选择dwm限制

**Comment by lastice** [comment]
请问是如何实现的 我安装Aero Glass之后还是有拖动延迟

**Comment by huhuime** [comment]
> 请问是如何实现的 我安装Aero Glass之后还是有拖动延迟

修改%UserProfile%.vscode\extensions\eyhn.vscode-vibrancy-1.0.9\src\extension.js
注销掉第143行opacity = 0;及第197行os === 'win10' ||
再修改扩展配置中透明度和毛玻璃效果类型为dwm最后重载（保存好修改文件再重置）

**Comment by lastice** [comment]
感谢 成功了

**Comment by EYHN** [comment]
The latest version (v1.0.10) contains a solution to the mouse lag, please see here for details.

Try the latest version. If the problem is not resolved, please update this issue.
