### ISSUE TITLE
1.43.0版本不受支持/Version 1.43.0 is not supported

### ISSUE THREAD

**Issue by you-hengh** [EYHN/vscode-vibrancy#48]
开发者,您好!

![image](https://user-images.githubusercontent.com/34816426/76502778-a3cd8200-647f-11ea-8865-b79ca492208b.png)

版本: 1.43.0
提交: 78a4c91400152c0f27ba4d363eb56d2835f9903a
日期: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 16.7.0

我非常喜欢这款插件的风格,但是在一次vscode的推送更新后,这个插件失效了,而我没有办法去降级安装vscode,所以希望开发者在空闲时间可以对插件版本进行升级,非常感谢!

I like the style of this plug-in very much, but after a push update of vscode, this plug-in failed, and I have no way to downgrade the installation of vscode, so I hope the developers can upgrade the version of the plug-in in their free time, thank you very much!

**Comment by huhuime** [comment]
请问看了这段话吗？
![image](https://user-images.githubusercontent.com/6631239/76503917-b052da00-6481-11ea-8132-f71e75b2fd52.png)
或者这段话吗？
![image](https://user-images.githubusercontent.com/6631239/76503977-c2347d00-6481-11ea-9a4e-152114e5e3de.png)

**Comment by you-hengh** [comment]
> 请问看了这段话吗？
> ![image](https://user-images.githubusercontent.com/6631239/76503917-b052da00-6481-11ea-8132-f71e75b2fd52.png)
> 或者这段话吗？
> ![image](https://user-images.githubusercontent.com/6631239/76503977-c2347d00-6481-11ea-9a4e-152114e5e3de.png)

非常感谢回复,虽然在使用这款插件,但其实对它的一些设置并不是很熟悉,现在已经可以正常使用了,再次感谢!
