### ISSUE TITLE
调整设置更改透明度无效/卸载后亚克力效果还在/卸载后更换其它主题后亚克力效果还在

### ISSUE THREAD

**Issue by zero-ven** [EYHN/vscode-vibrancy#54]
win10 2004 19041.264
vscode 1.45.1
Vibrancy 1.09.1

**Comment by huhuime** [comment]
教程不是写了
![image](https://user-images.githubusercontent.com/6631239/83322196-3237ef80-a288-11ea-95fb-ad85d7c795fc.png)
![image](https://user-images.githubusercontent.com/6631239/83322201-3a902a80-a288-11ea-8a7a-5dd2db77f4cd.png)
