### ISSUE TITLE
windows 1909切换桌面的时候，背景会变成透明

### ISSUE THREAD

**Issue by lyandzao** [EYHN/vscode-vibrancy#55]
![image](https://user-images.githubusercontent.com/33866716/84109399-29e46f00-aa55-11ea-8704-64b7210a3d86.png)

**Comment by HO-COOH** [comment]
Might be the same bug: It works correctly on my primary monitor but it becomes transparent (instead of blur) on my secondary monitor.

**Comment by EYHN** [comment]
Try the latest version. If the problem is not resolved, please update this issue.
