### ISSUE TITLE
wsl: Arch(remote) 无法无法启动 Vibrancy

### ISSUE THREAD

**Issue by RungeCC** [EYHN/vscode-vibrancy#62]
## 背景信息

- OS:                        Arch Linux (on the Windows Subsystem for Linux)
- Kernel:                  x86_64 Linux 4.19.104-microsoft-standard
- VSCode version:   1.48.0-insider(62503719349d04686a0704f7646b761aaf495b3d) x64
- Vibrancy version: latest, 1.0.9

## 错误信息 

当从命令面板使用命令 `Enable Vibrancy` 的时候出现错误：
```
Command 'Enable Vibrancy' resulted in an error 
(ENOENT: no such file or directory, stat 
'<path/to/myhome>/.vscode-server-insiders/bin/62503719349d04686a0704f7646b761aaf495b3d/out/main.js')
```

## 补充说明

所指向的文件夹 `path/to/myhome/.vscode-server-insiders/bin/62503719349d04686a0704f7646b761aaf495b3d/out/`
其下是：
```
total 76K
-rw-r--r-- 1 1.2K Aug  4 13:02 bootstrap-amd.js
-rw-r--r-- 1 2.9K Aug  4 13:02 bootstrap-fork.js
-rw-r--r-- 1 2.9K Aug  4 13:02 bootstrap.js
-rw-r--r-- 1 1.1K Aug  4 13:02 bootstrap-node.js
-rw-r--r-- 1 52K  Aug  4 13:19 nls.metadata.json
-rw-r--r-- 1 1.2K Aug  4 13:02 paths.js
drwxr-xr-x 5 4.0K Aug  4 14:56 vs
```
可以找到 `main.js` 位于 `./vs/server/main.js`

**Comment by RungeCC** [comment]
如果在 windows 上成功启动了 vibrancy 那么显示是正常的。
但是不能在仍然会遇到上面的问题。

**Comment by EYHN** [comment]
This extension does not support vscode remote. Please install locally.
