### ISSUE TITLE
mac 11 big sur 失效

### ISSUE THREAD

**Issue by FangyimingLode** [EYHN/vscode-vibrancy#71]
您好  mac big sur 没有管理员权限
![image](https://user-images.githubusercontent.com/57992882/95649300-70cf9780-0b0f-11eb-9370-d02a92fdcd11.png)

**Comment by EYHN** [comment]
What you see is a new security "feature" in Mac 10.12. If you try to launch an app from the Downloads folder, a "Gatekeeper" moves to and launches the app from a read-only folder.  You can move the Vistual Studio Code app bundle into /Applications before launching. This may be able to solve this problem.
