### ISSUE TITLE
Blur remains after disabling / uninstanlling

### ISSUE THREAD

**Issue by office-chair** [EYHN/vscode-vibrancy#75]
I wanted to switch to light mode, for which I'd need to disable Vibrancy, but upon disabling it and switching to Light Mode (and then reloading) I got this:

![image](https://user-images.githubusercontent.com/69007360/102143887-85f0db80-3e5c-11eb-8cd6-c827811d77ed.png)

Uninstalling doesn't work either. Why is that?

**Comment by maxoyed** [comment]
How do you fix it?
