### ISSUE TITLE
How to install on linux

### ISSUE THREAD

**Issue by coolbeatz71** [EYHN/vscode-vibrancy#76]
When I try to install it in ubuntu, I'm getting the following error, even I run vscode as root 

```
Command 'Enable Vibrancy' resulted in an error (EROFS: read-only file system, open '/snap/code/52/usr/share/code/resources/app/out/main.js')
```

**Comment by pkkid** [comment]
This extension does not support Linux.
See existing bug: https://github.com/EYHN/vscode-vibrancy/issues/20

**Comment by EYHN** [comment]
same: #20
