### ISSUE TITLE
Feature suggestion setting:  "vscode_vibrancy.limit"

### ISSUE THREAD

**Issue by mkanet** [EYHN/vscode-vibrancy#8]
Vibrancy looks best with a low opacity setting such as, "0.2".

However, the vibrancy effect looks very bad when VSCode is on top of a very bright/white background.  Example:
![Screenshot](https://user-images.githubusercontent.com/811008/62434516-72245980-b6ed-11e9-9f9d-7df62c25f187.png)

It would be great to offer a setting to limit opacity range, if possible.  That way, the vibrancy effect will always look great.

**Comment by EYHN** [comment]
This plugin works with the native interface provided by windows. I can't change what the effect looks like.

**Comment by AmrBinBashir** [comment]
@mkanet You can choose what to be vibrant and what not, beside different opacity for each element in the css file.
