### ISSUE TITLE
Vibrancy (v1.0.10) relative path changed in CSS files

### ISSUE THREAD

**Issue by mkanet** [EYHN/vscode-vibrancy#81]
In all previous versions of Vibrancy, I used to be able to add code like below to: **Default Dark.css**

```
.monaco-editor .inline-folded, body {
  background-image: url(../themes/images/mycustomicon.png);
}
```
It would use the relative path below (as expected):
`file:///C:/Users/username/.vscode/extensions/eyhn.vscode-vibrancy-xx.xxx`

However, after I upgraded to Vibrancy (v1.0.10), the relative path has changed to:
`file:///C:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser`

How do I change the relative path back to the previous way?  I would expect the default relative path to be relative to the extension (like all the other files in the extension).  I'm guessing the changes in **..\extension\index.js** probably caused this issue.  I'm hoping there's an easy way to get the CSS files to use the expected relative path as before.

Thank you so much if you can help with this!

**Comment by EYHN** [comment]
There is a way to insert custom CSS file, 

* **First create a custom css file.**

  custom-style.css
  ``` css
  .monaco-editor .inline-folded, body {
    background-image: url('./mycustomicon.png') !important;
  }
  ```
* **Add the following code to the global `settings.json` of vscode.**
  ``` json
  "vscode_vibrancy.imports": [
      "<path-to-file>/custom-style.css",
      "$theme-style$"
  ]
  ```

**Comment by mkanet** [comment]
Thanks.  I have a VSCode Extension Theme that uses Vibrancy to add transparency blur effect and custom images.  Before, I could just use a single CSS file that was part of my Extension:

```
.monaco-editor .inline-folded, body {
  background-image: url(../themes/images/mycustomicon.png);
}
```

**Comment by mkanet** [comment]
Thank you.  I am hoping you can still help me.  I have a special case...

I have a VSC Extention (VSCode theme) that uses Vibrancy Blur effect to enhance the theme.  I am very thankful for that!  I was able to use the below CSS file for custom styles located at the below path (after my extension is installed):

`C:\Users\MKANET\.vscode\extensions\mkanet.mkanet-theme-v2-x-x-.x\themes\MKA-Dark.css`.  

In this file, all css styles work correctly as expected... however, when I reference image files relative to my Extension's path like below, the relative paths no longer works correctly. 

**MKA-Dark.css**
```
.monaco-editor .inline-folded, body {
  background-image: url(../themes/images/mycustomicon.png);
}
```
I'm not sure what path to use since I can't use hard-coded paths in an extension.  I'm not how to specify variables 

Also, I'm not sure how to make your suggestion automatic when installing the extension from VSCode Market.
 
I would really appreciate your help! :)

**Comment by EYHN** [comment]
Sorry to reply to you so late.

After v1.0.10, this extension will write the theme css style to vscode's `main.js` as a string during installation. This is to ensure that the dynamic blur effect does not depend on other files in the extension directory, and that the dynamic blur effect will not be affected when the files are deleted or moved when the extension is deleted or updated. But this affects the relative paths of the external files referenced in css, causing your problem.

As I replied before, you can add "vscode_vibrancy.imports" attribute in setting.json to import "custom-style.css", in "custom-style.css" The relative path is relative to this css file. This method is supported by this extension for custom css.

I understand that you want to develop your own extension based on this extension, you can use the following method to automatically insert the "vscode_vibrancy.imports" property in setting.json.

``` js
await vscode.workspace.getConfiguration()
  .update(
    "vscode_vibrancy.imports",
    [
      // Using "context.extensionPath" you can get the extension directory
      // and calculate the absolute path to the css file
      path.join(context.extensionPath, 'themes', 'MKA-Dark.css'), // C:\Users\MKANET\.vscode\extensions\mkanet.mkanet-theme-v2-x-x-.x\themes\MKA-Dark.css
      "$theme-style$"
    ],
    vscode.ConfigurationTarget.Global);

```

Or you still want to import external files with relative paths via theme css file, you need to modify extension/index.js and runtime/index.js of the extension.  Here is how to modify it based on https://github.com/EYHN/vscode-vibrancy/commit/a9e335ea1d71d56c4815b3560d8a39d783a0a71b.

extension/index.js near line 131

``` diff
async function installJS() {
	const config = vscode.workspace.getConfiguration("vscode_vibrancy");
	const currentTheme = getCurrentTheme(config);
	const themeConfig = require(path.resolve(__dirname, themeConfigPaths[currentTheme]));
-	const themeCSS = await fs.readFile(path.join(__dirname, themeStylePaths[currentTheme]), 'utf-8');
+	const themeCSSPath = path.join(__dirname, themeStylePaths[currentTheme]);

	const JS = await fs.readFile(JSFile, 'utf-8');

	const injectData = {
		os: os,
		config: config,
		theme: themeConfig,
-		themeCSS: themeCSS
+		themeCSSPath: themeCSSPath
	}
```

runtime/index.js near line 166
``` diff
	const HTML = [
		`
		<style>
			html {
				background: rgba(${backgroundRGB.r},${backgroundRGB.g},${backgroundRGB.b},${opacity}) !important;
			}
		</style>
		`,
		`
-		<style>
- 			${app.themeCSS}
- 		</style>
+ 		<link rel="stylesheet" href="${app.themeCSSPath}"/>
		`,
		...customImports.css
	]

	return HTML.join('')
}
```

Hope this solves your problem and thank you for using this extension.

**Comment by mkanet** [comment]
Wow.  THANK YOU!  I think I prefer to keep things as simple as possible... My extension currently has only two theme styles (MKA-Dark, and MKA-Lighter). `MKA-Dark` is the default theme style for my extension.  It is probably easier for me to just modify `extension/index.js` and `runtime/index.js1`; keeping everything else the same.

**Also, what do you think about this solution?**
Instead of modifying your Vibrancy code in my extension... what if I just change my CSS files like this. 

**MKA-dark.css** (original):
```
.monaco-editor .inline-folded, body {
  background-image: url(../themes/images/fold.png);
  background-repeat: no-repeat;
  background-size: contain;
}
```
**MKA-dark.css** (new):
```
.monaco-editor .inline-folded, body {
  background-image: url(https://raw.githubusercontent.com/mkanet/MKANET-Theme-V2/master/themes/images/fold.png);
  background-repeat: no-repeat;
  background-size: contain;
}
```
Are there any disadvantages to using Internet-based URLs instead of local files?  I'm not certain, but it looks like VSCode caches these images.  If there are no issues doing it this way, it would be the simplest solution.. plus, it would be easier for me to update my copy of Vibrancy (if you make changes to your Vibrancy code).  What do you think?

Again, thank you so much for all your help!

**Comment by EYHN** [comment]
Sorry, there is a small problem in the code I gave before.

On line 166 in `runtime/index.js`
`<link rel="stylesheet" href="${app.themeCSSPath}"/>`
should be changed to
`<link rel="stylesheet" href="file://${app. themeCSSPath}"/>`
and it will work fine.

**Comment by EYHN** [comment]
About your question.
If the graphic file is not very large, I suggest you use base64 image as the background image. base64 images are not network dependent and have no relative path issues, which is perfect for your use case. There is a detailed tutorial on how to use base64 here.

https://www.base64-image.de/tutorial

It looks like this

```
.monaco-editor .inline-folded, body {
  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAzUlEQVQ4je2SMQrCQBBFX2EvHsJWbNMpeAltLYIhtWihkMBAMiA5hCCSkyikS+ERxNZCtFqb3YCNLmjpwC8G/n8w/IH/AJDn+TDLskpVjY9EpA7DcAy0AVDVS32Mze088VJ9jI2IXIGBA3iHnVTVAPMXwH67NvvtujG92y1g8wIodytT7lZN4N1uAcW3JxSuhcupmnmHT9XMJElyb06IomgqIlffGtM0fQRBcAAW7hU6wAhYWmrxQRvrHTlAy0K6QA/of1DPejvfPPBv5gnDgVHR+bNrGAAAAABJRU5ErkJggg==");
  background-repeat: no-repeat;
  background-size: contain;
}
```

**Comment by mkanet** [comment]
> Sorry, there is a small problem in the code I gave before.
> 
> On line 166 in `runtime/index.js`
> `<link rel="stylesheet" href="${app.themeCSSPath}"/>`
> should be changed to
> `<link rel="stylesheet" href="file://${app. themeCSSPath}"/>`
> and it will work fine.

Thank you.  I feel very bad for taking so much of your time.  Unfortunately, this still doesn't make any difference.  It looks like the CSS file isn't being loaded at all. 

I also tried changing that line to below (removing the extra space).  It still didn't make any difference.  It looks like the CSS file is still not being loaded.

`<link rel="stylesheet" href="file://${app.themeCSSPath}"/>`

Does it work for you?

**Comment by mkanet** [comment]
> About your question.
> If the graphic file is not very large, I suggest you use base64 image as the background image. base64 images are not network dependent and have no relative path issues, which is perfect for your use case. There is a detailed tutorial on how to use base64 here.
> 
> https://www.base64-image.de/tutorial
> 
> The code looks like this
> 
> ```
> .monaco-editor .inline-folded, body {
>   background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAzUlEQVQ4je2SMQrCQBBFX2EvHsJWbNMpeAltLYIhtWihkMBAMiA5hCCSkyikS+ERxNZCtFqb3YCNLmjpwC8G/n8w/IH/AJDn+TDLskpVjY9EpA7DcAy0AVDVS32Mze088VJ9jI2IXIGBA3iHnVTVAPMXwH67NvvtujG92y1g8wIodytT7lZN4N1uAcW3JxSuhcupmnmHT9XMJElyb06IomgqIlffGtM0fQRBcAAW7hU6wAhYWmrxQRvrHTlAy0K6QA/of1DPejvfPPBv5gnDgVHR+bNrGAAAAABJRU5ErkJggg==");
>   background-repeat: no-repeat;
>   background-size: contain;
> }
> ```

Thank you, this is a great idea.  My images are relatively small.  Maybe, I'll just use this method since the other way doesn't work correctly.  It might be better anyway for me to keep the index.js files the same as yours.
