### ISSUE TITLE
Doesn't work with Customize UI anymore

### ISSUE THREAD

**Issue by itstommi** [EYHN/vscode-vibrancy#86]
This has been a problem for a couple of weeks and I just ignored it because I wasn't using VS Code all that often, but I can't figure out why it doesn't work with Customize UI anymore and it's a little annoying because I loved this plugin.

**Comment by myzenon** [comment]
Me too. At first, I try to find out why this extension doesn't work any more. After I disabled the ` Customize UI ` extension, It works. I'm not sure which extension cause this problem. Please find a fix for this. I loved this extension so much.

**Comment by EYHN** [comment]
Has been fixed in v1.0.14.

Try the latest version. If the problem is not resolved, please update this issue.

**Comment by evolify** [comment]
The latest version still has the issue
