### ISSUE TITLE
No longer works on linux (Used to work on KDE PLASMA)

### ISSUE THREAD

**Issue by ckissane** [EYHN/vscode-vibrancy#87]
Contrary to the belief of the unsupported OS error message it now gives it did work earlier (in combo with the code-transparent AUR package). Please remove the error message so it can continue to work.

**Comment by EYHN** [comment]
Seems to work, but I don't currently have a computer with kde installed for testing. If you need this extension on linux you can make a copy yourself.

**Comment by ckissane** [comment]
@EYHN I do though, If you want help I can definitely provide some. Should I fork and make a PR?

**Comment by vivekmiyani** [comment]
@ckissane Did you manage to work it on linux?

**Comment by ckissane** [comment]
Just use vscode-transparent package on arch linux

**Comment by ckissane** [comment]
Or use my vscode fork which has some transparency built into some of the themes
